run:
  timeout: 10m
  go: "1.23.2"
  allow-parallel-runners: true
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - copyloopvar
    - gci
    - goconst
    - gocritic
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wsl

linters-settings:
  depguard:
    rules:
      main:
        files:
          - "$all"
        deny:
          - pkg: "github.com/OpenPeeDeeP/depguard"
            desc: ""
  godot:
    #   declarations - for top level declaration comments (default);
    #   toplevel     - for top level comments;
    #   all          - for all comments.
    scope: toplevel
    exclude:
      - '^ \+.*'
      - '^ ANCHOR.*'
  gci:
    sections:
      - "standard"
      - "default"
      - "prefix(git.sbercloud.tech)"
      - "prefix(git.sbercloud.tech/devplatform/cloud_scan)"
    custom-order: true
  importas:
    no-unaliased: true
    alias:
      # Foundation
      - pkg: git.sbercloud.tech/products/paas/shared/foundation/management-server
        alias: mgmtserver
  nolintlint:
    allow-unused: false
    require-specific: false
  revive:
    rules:
      # The following rules are recommended https://github.com/mgechev/revive#recommended-configuration
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      #
      # Rules in addition to the recommended configuration above.
      #
      - name: bool-literal-in-expr
      - name: constant-logical-expr
  gosec:
    excludes:
      - G307 # Deferring unsafe method "Close" on type "\*os.File"
      - G108 # Profiling endpoint is automatically exposed on /debug/pprof
      - G204 # Subprocess launched with variable 
  stylecheck:
    checks:
      - "all"
      - "-ST1000"
      - "-ST1003"
      - "-ST1016"
      - "-ST1020"
      - "-ST1021"
      - "-ST1022"
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - performance
    disabled-checks:
      - appendAssign
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - evalOrder
      - ifElseChain
      - octalLiteral
      - regexpSimplify
      - sloppyReassign
      - truncateCmp
      - typeDefFirst
      - unnamedResult
      - unnecessaryDefer
      - whyNoLint
      - wrapperFunc
      - rangeValCopy
      - hugeParam

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # We are disabling default golangci exclusions because we want to help reviewers to focus on reviewing the most relevant
  # changes in PRs and avoid nitpicking.
  exclude-use-default: false
  exclude-rules:
    # Disable unparam "always receives" which might not be really
    # useful when building libraries.
    - linters:
        - unparam
      text: always receives
    - path: _test\.go
      text: cyclomatic complexity
    # We don't care about repeatable data in test files.
    - linters:
        - goconst
      path: _test\.go